# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-19 18:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Archivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion_mac', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Grupo_Dispositivos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Lista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='grupo_dispositivos',
            name='lista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='srv.Lista'),
        ),
        migrations.AddField(
            model_name='grupo_dispositivos',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='srv.Usuario'),
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='srv.Grupo_Dispositivos'),
        ),
        migrations.AddField(
            model_name='archivo',
            name='lista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='srv.Lista'),
        ),
        migrations.AddField(
            model_name='archivo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='srv.Usuario'),
        ),
    ]
