# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-02 20:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srv', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivo',
            name='url',
            field=models.CharField(default='https://ia801609.us.archive.org/13/items/video_rapid_201703/video_rapid_240x350.mp4', max_length=200),
        ),
    ]
