# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-02 20:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srv', '0002_archivo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivo',
            name='time',
            field=models.IntegerField(null=True),
        ),
    ]
