# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-03 03:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('srv', '0005_auto_20180103_0201'),
    ]

    operations = [
        migrations.RenameField(
            model_name='archivo',
            old_name='time',
            new_name='tiempo',
        ),
        migrations.RemoveField(
            model_name='archivo',
            name='user',
        ),
    ]
