# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-04 16:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('srv', '0007_auto_20180103_0331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispositivo',
            name='grupo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='srv.GrupoDispositivos'),
        ),
        migrations.AlterField(
            model_name='grupodispositivos',
            name='lista',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='srv.Lista'),
        ),
    ]
